USB_VID = 0x303A
USB_PID = 0x825F
USB_MANUFACTURER = "Waveshare Electronics"
USB_PRODUCT = "ESP32-S3 Touch LCD 2.8"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m
