USB_VID = 0x1B4F
USB_PID = 0x0038
USB_PRODUCT = "klavecimbel.com RP2350B MCU Dev Board"
USB_MANUFACTURER = "klavecimbel.com"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = B
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ"

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel/

CIRCUITPY_USB_HOST = 0

CIRCUITPY__EVE = 0

CIRCUITPY_CYW43 = 0
CIRCUITPY_SSL = 0
CIRCUITPY_HASHLIB = 0
CIRCUITPY_WEB_WORKFLOW = 0
CIRCUITPY_MDNS = 0
CIRCUITPY_SOCKETPOOL = 0
CIRCUITPY_WIFI = 0


# Must be accompanied by a linker script change
CFLAGS += -DCIRCUITPY_FIRMWARE_SIZE='(1536 * 1024)'
