USB_VID = 0x303A
USB_PID = 0x830B

USB_PRODUCT = "DinMeter"
USB_MANUFACTURER = "M5Stack"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB

# Very few pins.
CIRCUITPY_ESPCAMERA = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
