USB_VID = 0x04D8
USB_PID = 0xE52B
USB_PRODUCT = "Microchip Curiosity CircuitPython"
USB_MANUFACTURER = "Microchip Technology Inc"

CHIP_VARIANT = SAME51J20A
CHIP_FAMILY = same51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "SST26VF016B,SST26VF032B,SST26VF064B"
LONGINT_IMPL = MPZ

CIRCUITPY__EVE = 1
CIRCUITPY_CANIO = 1
